#服务名
spring:
  application:
    name: mail-to-zentao-demo-dev
#  boot:
#    admin:
#      client:
#        url: http://192.168.0.46:5000
  datasource: 
      url: jdbc:mysql://192.168.2.75:3306/zentao_test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
      username: wds
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid: 
#      # 配置Druid的其他参数，以下配置必须增加一个配置文件才能有效
#      # 初始化大小，最小，最大
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      # 获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      # ！！！请勿配置timeBetweenLogStatsMillis 会定时输出日志 并导致统计的sql清零
#      #spring.datasource.druid.timeBetweenLogStatsMillis=20000
#      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#      #是否启用StatFilter默认值true
#      web-stat-filter:
#        enabled: true
#        #url-pattern: com.vst.mapper.*,com.vst.service.*,com.vst.web.controller.*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
#        #是否启用StatViewServlet默认值true
#      stat-view-servlet:
#        enabled: true  
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin
#        login-password: admin

#eureka 服务发现    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.0.46:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
      
####spring-boot-admin 配置##
#health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。   
#management: 
#  endpoint: 
#    health: 
#      show-details: ALWAYS 
#  endpoints:
#    web:
#      exposure: 
#        include: "*" #暴露所有端点
####项目信息##
info: 
  app: 
    name: mail-to-zentao-demo
    description: 禅道邮件
    version: 1.0
    
####服务器信息
server:
  port: 2333
  session-timeout: 60
  tomcat:
    uri-encoding: UTF-8
  timezone: GMT+00:00
    
    
#######日志
logging:
  file: log/mail_to_zentao_demo.log
  config: classpath:logback-spring.xml
  
####mybatis配置
mybatis:
  type-aliases-package: com.vst.pojo
  mapper-locations: classpath:mapper/*.xml
  mappers: com.vst.base.BaseMapper
  not-empty: false
  identity: MYSQL
  
  
##zentao_config
zentao:
  url: http://192.168.2.20:80
  account: admin
  password: 123QWEasd
  session_id_path: /pro/api-getSessionID.json
  refer_to: /pro/my/
  exec_method_path: /pro/api-getModel-%d-%d-%d.json
  login_path: /pro/user-login.json?
  logout_path: /pro/user-logout.json
  bug_browse_path: /pro/bug-browse-1.json
  bug_create_path: /pro/bug-create-1-0-moduleID=0.json?
  
  
###mail_config
mail:
  smtp_server: smtp.qq.com
  smtp_port: 587 #465
  imap_server: imap.qq.com
  imap_port: 993
  pop_server: pop.qq.com
  pop_port: 995
  mailbox: 714413099@qq.com
  pop_password: aanfoofqvrwtbcea
  imap_password: sqwjwocdyxfwbeah
  
job: 
  timer: 
    "0 0/1 * * * ?"

period: 60000
